#!/usr/bin/env python3

'''The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?'''

import math

def number_of_divisors(number) :
    divs = 0

    root = int(math.ceil(math.sqrt(number)))
    if root**2 == number :
        divs -= 1
    for i in range(1, root) :
        if number % i == 0 :
            divs += 2
    return divs

i = 1
inc = 2

divs = 0

while divs < 500 :
    i = i + inc
    inc += 1
    divs = number_of_divisors(i)
    print(i, divs)
print(i)
