#!/usr/bin/env python3

'''Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle T_n=n(n+1)/2 1, 3, 6, 10, 15, ...
Pentagonal P_n=n(3n−1)/2 1, 5, 12, 22, 35, ...
Hexagonal H_n=n(2n−1) 1, 6, 15, 28, 45, ...
It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.'''

tb = 285 + 1
pb = 165
hb = 143
tria = int(tb*(tb+1)/2)
tb += 1 
pent = 40755
hexa = 40755

while tria != pent or tria != hexa :
    if pent > tria or hexa > tria :
        tria = int(tb*(tb+1)/2)
        tb += 1

    if pent < tria :
        pent = int(pb*(3*pb-1)/2)
        pb += 1

    if hexa < tria :
        hexa = hb*(2*hb-1)
        hb += 1

print(tria)
